#!/bin/bash
lfi-compile clang \
    -mllvm --reserve-r14 -mllvm --reserve-r15 -mllvm -align-labels=16 \
    "$@" \
    -fuse-ld=lld \
    -fPIC \
    -Wno-unused-command-line-argument \
    -target x86_64-linux-musl
