#!/bin/bash
TOOLCHAIN=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/..
lfi-compile clang \
    -mllvm --reserve-r14 -mllvm --reserve-r15 -mllvm -align-labels=16 \
    "$@" \
    --sysroot $TOOLCHAIN/sysroot \
    --rtlib=compiler-rt \
    -resource-dir $TOOLCHAIN/compiler-rt \
    -nostdlibinc \
    -isystem $TOOLCHAIN/sysroot/include \
    -isystem /usr/include \
    -isystem /usr/include/x86_64-linux-gnu \
    -fuse-ld=lld \
    -Wno-unused-command-line-argument \
    -static-pie \
    -target x86_64-linux-musl
